server:
  port: 8085
spring:
  application:
    name: discount
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: "true"
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud5
    username: root
    password: 1234

