package p4RetrievingAutoGeneratedKeys;

import org.springframework.context.support.GenericXmlApplicationContext;

public class Test {
    public static void main(String[] args) {
        var context=new GenericXmlApplicationContext();
        context.load("file:C:\\Users\\Admin\\IdeaProjects\\spring\\5\\session8\\01-SpringJdbc-DataAccessWithJDBC\\src\\main\\java\\p4RetrievingAutoGeneratedKeys\\config.xml");
        context.refresh();

        final EmployeeDao bean = context.getBean("dao3",EmployeeDao.class);
        final Number number = bean.CreateEmployee();
        System.out.println("AutoGeneratedKeys is : "+number);
    }
}
