spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch2
    username: root
    password: 1234
  batch:
    job:
      enabled: false

#  batch:
#    jdbc:
#      initialize-schema: always
